### PR TITLE
fix(requirements) crucial updates

### PR DESCRIPTION
**Pull request by benetis**

### CODE REVIEW

**Review by gloomy — CHANGES_REQUESTED** [review]
Missing descriptive description with argument-ed arguments

**Comment by benetis** [comment]
Arguments don't matter in politics, only who has a majority vote

**Comment by benetis** [comment]
I added additional update due recent events:

https://www.delfi.lt/news/daily/education/streikuojantys-mokytojai-reikalauja-ne-tik-pinigu-patys-prie-to-privede.d?id=82899283

```
Mokytojas P. Bakanas teigė, kad „gerai būtų mokytojui žinoti, kur eina švietimas“.
```

I thought it must be important for us too + removed PHP completely to make it programming language agnostic.

**Comment by gloomy** [comment]
vogon

**Pull request closed without merging**
